# Dockerfile

# Use ruby image to build our own image
FROM --platform=linux/x86_64 ruby:3.1.4-alpine3.19 AS base

# Ensure that we work in UTF 8
ENV LANG='C.UTF-8'
ENV LANGUAGE='C.UTF-8'

# Let the build process set a version for Plano that we can
# get at build and runtime
ARG PLANO_VERSION=''
ENV VITE_PLANO_VERSION=$PLANO_VERSION

ARG RAILS_ENV=production
ARG NODE_ENV=production

# Use a persistent volume for the gems installed by the bundler
ENV BUNDLE_PATH='/var/bundler'

ARG DEVISE_SECRET

RUN apk add \
      build-base \
      freetds-dev \
      less \
      netcat-openbsd \
      postgresql-client \
      postgresql-dev \
      pkgconfig \
      openssl \
      shared-mime-info \
      tzdata \
      yarn \
    && rm -rf /var/cache/apk/*

# Install bundler for this Docker image
RUN gem install bundler:2.3.26

# WORKDIR /setup
ADD . /opt/planorama
WORKDIR /opt/planorama

# Install Gems without the development packages
RUN bin/bundle install --without development

# Build the JS assets (also does the vite/yarn install)
RUN bin/rake assets:precompile

# We expose the port
EXPOSE 3000

# CMD script/planorama_start.sh
CMD ["tail", "-f", "/dev/null"]
