# Dockerfile

# Use ruby image to build our own image
FROM --platform=linux/x86_64 ruby:2.7.3-alpine as base

# Ensure that we work in UTF 8
ENV LANG C.UTF-8 # ensure that the encoding is UTF8
ENV LANGUAGE C.UTF-8 # ensure that the encoding is UTF8

ARG RAILS_ENV=production
ARG NODE_ENV=production

# Use a persistent volume for the gems installed by the bundler
ENV BUNDLE_PATH /var/bundler

ARG DEVISE_SECRET

RUN apk add \
      build-base \
      freetds-dev \
      less \
      netcat-openbsd \
      postgresql-client \
      postgresql-dev \
      pkgconfig \
      openssl \
      shared-mime-info \
      tzdata \
      yarn \
    && rm -rf /var/cache/apk/*

# Install bundler for this Docker image
RUN gem install bundler:2.2.4

# WORKDIR /setup
ADD . /opt/planorama
WORKDIR /opt/planorama

# Just not use dev here
RUN bin/bundle install --without development
RUN bin/yarn install --frozen-lockfile

# The precompile will also deal with the webpacker assets
# RUN bin/rake assets:precompile --trace # this fails, since we don't have any assets?

# We expose the port
EXPOSE 3000

# CMD script/planorama_start.sh
CMD ["tail", "-f", "/dev/null"]
