# Dockerfile

# Use ruby image to build our own image
# FROM --platform=linux/x86_64 ruby:3.1.4-alpine3.19 as base
FROM ruby:3.1.4-alpine3.19 as base

# Ensure that we work in UTF 8
ENV LANG='C.UTF-8'
ENV LANGUAGE='C.UTF-8'

# Specify an external volume for the Application source
VOLUME ["/opt/planorama"]
WORKDIR /opt/planorama

# Use a persistent volume for the gems installed by the bundler
ENV BUNDLE_PATH='/var/bundler'
ENV RAILS_ENV='development'

RUN apk add \
      build-base \
      freetds-dev \
      git \
      less \
      netcat-openbsd \
      postgresql-client \
      postgresql-dev \
      pkgconfig \
      openssl \
      shared-mime-info \
      tzdata \
      yarn \
    && rm -rf /var/cache/apk/*

# Install bundler for this Docker image
RUN gem install bundler:2.3.26

# pre-install bundle for speed later
ADD ./Gemfile /opt/planorama/Gemfile
RUN bundle install

# We expose the port
EXPOSE 3000

CMD ["tail", "-f", "/dev/null"]
